# Postgress
spring.datasource.url=jdbc:postgresql://localhost:5432/syshub
spring.datasource.username=postgres
spring.datasource.password=password

spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.highlight_sql=true

# JWT
jwt.secret.key=xqRSj0QFTZ8xEpszG6fWhuqLVqsbfz43C857pHWaJHq

# Mailer
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=syshubapp@gmail.com
spring.mail.password=ibslzoscyehzufwe 
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.debug=true

app.frontend.url=http://localhost:5173

# Storage
storage.location=/home/alejandro/Desktop/my-files/u/2026/ts1/syshub-uploads
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=15MB