# Configuración de la Fuente de Datos (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/syshub
spring.datasource.username=postgres
spring.datasource.password=password

# Driver de PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración adicional de JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.highlight_sql=true

# Configuracion JWT
jwt.secret.key=xqRSj0QFTZ8xEpszG6fWhuqLVqsbfz43C857pHWaJHq