spring.datasource.url=jdbc:postgresql://localhost:5432/syshub
spring.datasource.username=postgres
spring.datasource.password=password
jwt.secret.key=xqRSj0QFTZ8xEpszG6fWhuqLVqsbfz43C857pHWaJHq
spring.mail.username=syshubapp@gmail.com
spring.mail.password=ibslzoscyehzufwe
app.frontend.url=http://localhost:5173
storage.location=/home/alejandro/Desktop/my-files/u/2026/ts1/syshub-uploads
cloudinary.cloud-name=dj54vlrsd
cloudinary.api-key=729275814359759
cloudinary.api-secret=8bcq02YRXoB7UM16MdUHRmMMqNM